package com.selenium.browserinteractions;

public class Assignment6 {
    // DESIGN A SINGLE FILE SCRIPT WITH MULTIPLE TESTS
    // WHICH LAUNCHES A NEW BROWSER BEFORE EVERY TEST
    // INITIATES AN EXTENT REPORT BEFORE ALL
    // USES EXCEL SHEET TO FEED DATA INTO THE TESTS
    // DOES VALIDATION (SHOULD BE DYNAMIC) WITHIN TESTS
    // FLUSHES / PUBLISHES THE REPORT
}
