package com.corejava.assignments.composition;

public class Assignment {

    // CREATE A BASE CLASS CALLED AS COMPUTE
    // CREATE DIFFERENT CLASSES LIKE LAPTOP, DESKTOP, TABLET WHICH IS-A COMPUTE
    // CREATE DIFFERENT COMPONENTS LIKE MOTHERBOARD, SCREEN, OS
    // ASSEMBLE EACH DESKTOP, TABLET and LAPTOP WITH DIFFERENT MOTHERBOARDS, SCREEN AND OS
    // WRTIE GENERIC METHODS bootUp() and shutDown()
    // WRITE METHODS TO LAUNCH AN APP WHICH SHOULD ONLY BE POSSIBLE WHEN THE DEVICE IS ON
}
